### ISSUE TITLE
Progress bar scales opposite the cap motion

### ISSUE THREAD

**Issue by hexbenjamin** [navelpluisje/figma-slider-creator#2]
Hello! I am 1000% unsure if this is a bug, or operator error.

I'm trying to create a bottom-to-top slider sheet, and I'm getting this unusual behavior from my Progress element:

![image](https://github.com/user-attachments/assets/d766547f-731f-4c98-965b-b542ef9b6d56)

The Progress element is a duplicate of the Track element - both rounded rectangles (though I tried swapping the Progress to a line with a stroke as well).

Any ideas about what might be going on?

(also, thanks for a supremely useful utility)

**Comment by navelpluisje** [comment]
Hmm, looks like a bug to me. Will check what’s going on there. Can you supply a screenshot with the settings? Will help me debugging

**Comment by navelpluisje** [comment]
@hexbenjamin I've found the issue and have released a new version. Can you please validate the fix?

**Comment by hexbenjamin** [comment]
thanks so much for looking into it, and sorry i missed the first comment! I'll be able to test on about 20 minutes, I'll report back ASAP!

**Comment by hexbenjamin** [comment]
hello! sorry that took a little longer than planned! the range is good now, but unfortunately something does seem to be newly wrong with the caps. here's a more complete screenshot of the setup!

![image](https://github.com/user-attachments/assets/17f0f6cf-5b02-4aa2-b178-81393a3ea5b7)

**Comment by hexbenjamin** [comment]
in case it helps, I was just able to approximate a "correct" output with a workaround

the cap object in this case is 48px wide. so i moved the top of the cap-range object +48px in Y (downward) and scaled the height to -48px from its original size, and that does seem close!

![image](https://github.com/user-attachments/assets/16438440-3da3-48b8-a451-4a07499bb28b)

**Comment by navelpluisje** [comment]
That's weird. I created an example file with a horizontal and a vertical slider (will add it to the plugin as well) https://www.figma.com/design/DJ1kvFlye2eH01HnDK194h/Slider-Creator-Example-File?m=auto&t=2GkXp6yNjl6FqZrw-6

Can you please check if these are working for you?
As far as I can tell from the screenshots, it looks lke an issue with the `cap-range`

**Comment by hexbenjamin** [comment]
I cannot reproduce your success with my design. Your version works in my editor, but I have not been able to get any closer than this in 30 minutes. What exactly do you think is wrong with my cap range? Do I **need** a background shape (my grey rectangle is currently the cap range)?

![image](https://github.com/user-attachments/assets/90f9335f-dc90-495c-8752-22cbd3691193)

**Comment by navelpluisje** [comment]
Are you able to share this part of your file?

**Comment by hexbenjamin** [comment]
Sure! Sorry for the headaches with this!

**Comment by navelpluisje** [comment]
@hexbenjamin I found the issue. Not quite sure why, but it is at least fixable in the designs.
I changed the cap group into a frame and select `Clip Content`. Then it should work. It looks/feels like one of the (masked) layers is actually bigger then the group.
By clipping you at least know the exact boundaries

**Comment by hexbenjamin** [comment]
THANK you!!! its the grain overlay, i'm fairly new to Figma & didn't know that about clip groups! thank you so much again for taking the time on this!!

**Comment by navelpluisje** [comment]
You're welcome

**Comment by navelpluisje** [comment]
@hexbenjamin I've removed the link from your comment.
